export enum SummaryCardEnum {
  CURRENT_MONTH_ONBOARDING = 'CURRENT_MONTH_ONBOARDING',
  PREVIOUS_MONTH_ONBOARDING = 'PREVIOUS_MONTH_ONBOARDING',
  CURRENT_MONTH_REVENUE = 'CURRENT_MONTH_REVENUE',
  PREVIOUS_MONTH_REVENUE = 'PREVIOUS_MONTH_REVENUE',
}
