const CITY_OPTIONS: any[] = [
  { name: 'Adilabad', value: 'ADILABAD' },
  { name: 'Agar Malwa', value: 'AGAR MALWA' },
  { name: 'Agatti', value: 'AGATTI' },
  { name: 'Agra', value: 'AGRA' },
  { name: 'Ahmedabad', value: 'AHMEDABAD' },
  { name: 'Ahmednagar', value: 'AHMEDNAGAR' },
  { name: 'Aizawl', value: 'AIZAWL' },
  { name: 'Ajmer', value: 'AJMER' },
  { name: 'Akola', value: 'AKOLA' },
  { name: 'Alappuzha', value: 'ALAPPUZHA' },
  { name: 'Aligarh', value: 'ALIGARH' },
  { name: 'Alipurduar', value: 'ALIPURDUAR' },
  { name: 'Alirajpur', value: 'ALIRAJPUR' },
  { name: 'Allahabad', value: 'ALLAHABAD' },
  { name: 'Almora', value: 'ALMORA' },
  { name: 'Alwar', value: 'ALWAR' },
  { name: 'Ambala', value: 'AMBALA' },
  { name: 'Ambedkar Nagar', value: 'AMBEDKAR NAGAR' },
  {
    name: 'Amethi (Chatrapati Sahuji Mahraj Nagar)',
    value: 'AMETHI (CHATRAPATI SAHUJI MAHRAJ NAGAR)',
  },
  { name: 'Amini', value: 'AMINI' },
  { name: 'Amravati', value: 'AMRAVATI' },
  { name: 'Amreli', value: 'AMRELI' },
  { name: 'Amritsar', value: 'AMRITSAR' },
  { name: 'Amroha (J.P. Nagar)', value: 'AMROHA (J.P. NAGAR)' },
  { name: 'Anand', value: 'ANAND' },
  { name: 'Anantapur', value: 'ANANTAPUR' },
  { name: 'Anantnag', value: 'ANANTNAG' },
  { name: 'Androth', value: 'ANDROTH' },
  { name: 'Angul', value: 'ANGUL' },
  { name: 'Anjaw', value: 'ANJAW' },
  { name: 'Anuppur', value: 'ANUPPUR' },
  { name: 'Araria', value: 'ARARIA' },
  { name: 'Aravalli', value: 'ARAVALLI' },
  { name: 'Ariyalur', value: 'ARIYALUR' },
  { name: 'Arwal', value: 'ARWAL' },
  { name: 'Ashoknagar', value: 'ASHOKNAGAR' },
  { name: 'Auraiya', value: 'AURAIYA' },
  { name: 'Aurangabad', value: 'AURANGABAD' },
  { name: 'Aurangabad', value: 'AURANGABAD' },
  { name: 'Azamgarh', value: 'AZAMGARH' },
  { name: 'Bagalkot', value: 'BAGALKOT' },
  { name: 'Bageshwar', value: 'BAGESHWAR' },
  { name: 'Baghpat', value: 'BAGHPAT' },
  { name: 'Bahraich', value: 'BAHRAICH' },
  { name: 'Baksa', value: 'BAKSA' },
  { name: 'Balaghat', value: 'BALAGHAT' },
  { name: 'Balangir', value: 'BALANGIR' },
  { name: 'Balasore', value: 'BALASORE' },
  { name: 'Ballari (Bellary)', value: 'BALLARI (BELLARY)' },
  { name: 'Ballia', value: 'BALLIA' },
  { name: 'Balod', value: 'BALOD' },
  { name: 'Baloda Bazar', value: 'BALODA BAZAR' },
  { name: 'Balrampur', value: 'BALRAMPUR' },
  { name: 'Balrampur', value: 'BALRAMPUR' },
  { name: 'Banaskantha (Palanpur)', value: 'BANASKANTHA (PALANPUR)' },
  { name: 'Banda', value: 'BANDA' },
  { name: 'Bandipore', value: 'BANDIPORE' },
  { name: 'Banka', value: 'BANKA' },
  { name: 'Bankura', value: 'BANKURA' },
  { name: 'Banswara', value: 'BANSWARA' },
  { name: 'Barabanki', value: 'BARABANKI' },
  { name: 'Baramulla', value: 'BARAMULLA' },
  { name: 'Baran', value: 'BARAN' },
  { name: 'Bareilly', value: 'BAREILLY' },
  { name: 'Bargarh', value: 'BARGARH' },
  { name: 'Barmer', value: 'BARMER' },
  { name: 'Barnala', value: 'BARNALA' },
  { name: 'Barpeta', value: 'BARPETA' },
  { name: 'Barwani', value: 'BARWANI' },
  { name: 'Bastar', value: 'BASTAR' },
  { name: 'Basti', value: 'BASTI' },
  { name: 'Bathinda', value: 'BATHINDA' },
  { name: 'Beed', value: 'BEED' },
  { name: 'Begusarai', value: 'BEGUSARAI' },
  { name: 'Belagavi (Belgaum)', value: 'BELAGAVI (BELGAUM)' },
  { name: 'Bemetara', value: 'BEMETARA' },
  { name: 'Bengaluru (Bangalore) Rural', value: 'BENGALURU (BANGALORE) RURAL' },
  { name: 'Bengaluru (Bangalore) Urban', value: 'BENGALURU (BANGALORE) URBAN' },
  { name: 'Betul', value: 'BETUL' },
  { name: 'Bhadohi', value: 'BHADOHI' },
  { name: 'Bhadradri Kothagudem', value: 'BHADRADRI KOTHAGUDEM' },
  { name: 'Bhadrak', value: 'BHADRAK' },
  { name: 'Bhagalpur', value: 'BHAGALPUR' },
  { name: 'Bhandara', value: 'BHANDARA' },
  { name: 'Bharatpur', value: 'BHARATPUR' },
  { name: 'Bharuch', value: 'BHARUCH' },
  { name: 'Bhavnagar', value: 'BHAVNAGAR' },
  { name: 'Bhilwara', value: 'BHILWARA' },
  { name: 'Bhind', value: 'BHIND' },
  { name: 'Bhiwani', value: 'BHIWANI' },
  { name: 'Bhojpur', value: 'BHOJPUR' },
  { name: 'Bhopal', value: 'BHOPAL' },
  { name: 'Bidar', value: 'BIDAR' },
  { name: 'Bijapur', value: 'BIJAPUR' },
  { name: 'Bijnor', value: 'BIJNOR' },
  { name: 'Bikaner', value: 'BIKANER' },
  { name: 'Bilaspur', value: 'BILASPUR' },
  { name: 'Bilaspur', value: 'BILASPUR' },
  { name: 'Birbhum', value: 'BIRBHUM' },
  { name: 'Bishnupur', value: 'BISHNUPUR' },
  { name: 'Biswanath', value: 'BISWANATH' },
  { name: 'Bithra', value: 'BITHRA' },
  { name: 'Bokaro', value: 'BOKARO' },
  { name: 'Bongaigaon', value: 'BONGAIGAON' },
  { name: 'Botad', value: 'BOTAD' },
  { name: 'Boudh', value: 'BOUDH' },
  { name: 'Budaun', value: 'BUDAUN' },
  { name: 'Budgam', value: 'BUDGAM' },
  { name: 'Bulandshahr', value: 'BULANDSHAHR' },
  { name: 'Buldhana', value: 'BULDHANA' },
  { name: 'Bundi', value: 'BUNDI' },
  { name: 'Burdwan (Bardhaman)', value: 'BURDWAN (BARDHAMAN)' },
  { name: 'Burhanpur', value: 'BURHANPUR' },
  { name: 'Buxar', value: 'BUXAR' },
  { name: 'Cachar', value: 'CACHAR' },
  { name: 'Central Delhi', value: 'CENTRAL DELHI' },
  { name: 'Chamarajanagar', value: 'CHAMARAJANAGAR' },
  { name: 'Chamba', value: 'CHAMBA' },
  { name: 'Chamoli', value: 'CHAMOLI' },
  { name: 'Champawat', value: 'CHAMPAWAT' },
  { name: 'Champhai', value: 'CHAMPHAI' },
  { name: 'Chandauli', value: 'CHANDAULI' },
  { name: 'Chandel', value: 'CHANDEL' },
  { name: 'Chandigarh', value: 'CHANDIGARH' },
  { name: 'Chandrapur', value: 'CHANDRAPUR' },
  { name: 'Changlang', value: 'CHANGLANG' },
  { name: 'Charaideo', value: 'CHARAIDEO' },
  { name: 'Charkhi Dadri', value: 'CHARKHI DADRI' },
  { name: 'Chatra', value: 'CHATRA' },
  { name: 'Chennai', value: 'CHENNAI' },
  { name: 'Chethlath', value: 'CHETHLATH' },
  { name: 'Chhatarpur', value: 'CHHATARPUR' },
  { name: 'Chhindwara', value: 'CHHINDWARA' },
  { name: 'Chhota Udepur', value: 'CHHOTA UDEPUR' },
  { name: 'Chikballapur', value: 'CHIKBALLAPUR' },
  {
    name: 'Chikkamagaluru (Chikmagalur)',
    value: 'CHIKKAMAGALURU (CHIKMAGALUR)',
  },
  { name: 'Chirang', value: 'CHIRANG' },
  { name: 'Chitradurga', value: 'CHITRADURGA' },
  { name: 'Chitrakoot', value: 'CHITRAKOOT' },
  { name: 'Chittoor', value: 'CHITTOOR' },
  { name: 'Chittorgarh', value: 'CHITTORGARH' },
  { name: 'Churachandpur', value: 'CHURACHANDPUR' },
  { name: 'Churu', value: 'CHURU' },
  { name: 'Coimbatore', value: 'COIMBATORE' },
  { name: 'Cooch Behar', value: 'COOCH BEHAR' },
  { name: 'Cuddalore', value: 'CUDDALORE' },
  { name: 'Cuttack', value: 'CUTTACK' },
  { name: 'Dadra & Nagar Haveli', value: 'DADRA & NAGAR HAVELI' },
  { name: 'Dahod', value: 'DAHOD' },
  {
    name: 'Dakshin Dinajpur (South Dinajpur)',
    value: 'DAKSHIN DINAJPUR (SOUTH DINAJPUR)',
  },
  { name: 'Dakshina Kannada', value: 'DAKSHINA KANNADA' },
  { name: 'Daman', value: 'DAMAN' },
  { name: 'Damoh', value: 'DAMOH' },
  { name: 'Dangs (Ahwa)', value: 'DANGS (AHWA)' },
  { name: 'Dantewada (South Bastar)', value: 'DANTEWADA (SOUTH BASTAR)' },
  { name: 'Darbhanga', value: 'DARBHANGA' },
  { name: 'Darjeeling', value: 'DARJEELING' },
  { name: 'Darrang', value: 'DARRANG' },
  { name: 'Datia', value: 'DATIA' },
  { name: 'Dausa', value: 'DAUSA' },
  { name: 'Davangere', value: 'DAVANGERE' },
  { name: 'Dehradun', value: 'DEHRADUN' },
  { name: 'Deogarh', value: 'DEOGARH' },
  { name: 'Deoghar', value: 'DEOGHAR' },
  { name: 'Deoria', value: 'DEORIA' },
  { name: 'Devbhoomi Dwarka', value: 'DEVBHOOMI DWARKA' },
  { name: 'Dewas', value: 'DEWAS' },
  { name: 'Dhalai', value: 'DHALAI' },
  { name: 'Dhamtari', value: 'DHAMTARI' },
  { name: 'Dhanbad', value: 'DHANBAD' },
  { name: 'Dhar', value: 'DHAR' },
  { name: 'Dharmapuri', value: 'DHARMAPURI' },
  { name: 'Dharwad', value: 'DHARWAD' },
  { name: 'Dhemaji', value: 'DHEMAJI' },
  { name: 'Dhenkanal', value: 'DHENKANAL' },
  { name: 'Dholpur', value: 'DHOLPUR' },
  { name: 'Dhubri', value: 'DHUBRI' },
  { name: 'Dhule', value: 'DHULE' },
  { name: 'Dibang Valley', value: 'DIBANG VALLEY' },
  { name: 'Dibrugarh', value: 'DIBRUGARH' },
  { name: 'Dima Hasao', value: 'DIMA HASAO' },
  { name: 'Dimapur', value: 'DIMAPUR' },
  { name: 'Dindigul', value: 'DINDIGUL' },
  { name: 'Dindori', value: 'DINDORI' },
  { name: 'Diu', value: 'DIU' },
  { name: 'Doda', value: 'DODA' },
  { name: 'Dumka', value: 'DUMKA' },
  { name: 'Dungarpur', value: 'DUNGARPUR' },
  { name: 'Durg', value: 'DURG' },
  { name: 'East Champaran (Motihari)', value: 'EAST CHAMPARAN (MOTIHARI)' },
  { name: 'East Delhi', value: 'EAST DELHI' },
  { name: 'East Garo Hills', value: 'EAST GARO HILLS' },
  { name: 'East Godavari', value: 'EAST GODAVARI' },
  { name: 'East Jaintia Hills', value: 'EAST JAINTIA HILLS' },
  { name: 'East Kameng', value: 'EAST KAMENG' },
  { name: 'East Khasi Hills', value: 'EAST KHASI HILLS' },
  { name: 'East Siang', value: 'EAST SIANG' },
  { name: 'East Sikkim', value: 'EAST SIKKIM' },
  { name: 'East Singhbhum', value: 'EAST SINGHBHUM' },
  { name: 'Ernakulam', value: 'ERNAKULAM' },
  { name: 'Erode', value: 'ERODE' },
  { name: 'Etah', value: 'ETAH' },
  { name: 'Etawah', value: 'ETAWAH' },
  { name: 'Faizabad', value: 'FAIZABAD' },
  { name: 'Faridabad', value: 'FARIDABAD' },
  { name: 'Faridkot', value: 'FARIDKOT' },
  { name: 'Farrukhabad', value: 'FARRUKHABAD' },
  { name: 'Fatehabad', value: 'FATEHABAD' },
  { name: 'Fatehgarh Sahib', value: 'FATEHGARH SAHIB' },
  { name: 'Fatehpur', value: 'FATEHPUR' },
  { name: 'Fazilka', value: 'FAZILKA' },
  { name: 'Ferozepur', value: 'FEROZEPUR' },
  { name: 'Firozabad', value: 'FIROZABAD' },
  { name: 'Gadag', value: 'GADAG' },
  { name: 'Gadchiroli', value: 'GADCHIROLI' },
  { name: 'Gajapati', value: 'GAJAPATI' },
  { name: 'Ganderbal', value: 'GANDERBAL' },
  { name: 'Gandhinagar', value: 'GANDHINAGAR' },
  { name: 'Ganjam', value: 'GANJAM' },
  { name: 'Garhwa', value: 'GARHWA' },
  { name: 'Gariyaband', value: 'GARIYABAND' },
  { name: 'Gautam Buddha Nagar', value: 'GAUTAM BUDDHA NAGAR' },
  { name: 'Gaya', value: 'GAYA' },
  { name: 'Ghaziabad', value: 'GHAZIABAD' },
  { name: 'Ghazipur', value: 'GHAZIPUR' },
  { name: 'Gir Somnath', value: 'GIR SOMNATH' },
  { name: 'Giridih', value: 'GIRIDIH' },
  { name: 'Goalpara', value: 'GOALPARA' },
  { name: 'Godda', value: 'GODDA' },
  { name: 'Golaghat', value: 'GOLAGHAT' },
  { name: 'Gomati', value: 'GOMATI' },
  { name: 'Gonda', value: 'GONDA' },
  { name: 'Gondia', value: 'GONDIA' },
  { name: 'Gopalganj', value: 'GOPALGANJ' },
  { name: 'Gorakhpur', value: 'GORAKHPUR' },
  { name: 'Gumla', value: 'GUMLA' },
  { name: 'Guna', value: 'GUNA' },
  { name: 'Guntur', value: 'GUNTUR' },
  { name: 'Gurdaspur', value: 'GURDASPUR' },
  { name: 'Gurgaon', value: 'GURGAON' },
  { name: 'Gwalior', value: 'GWALIOR' },
  { name: 'Hailakandi', value: 'HAILAKANDI' },
  { name: 'Hamirpur', value: 'HAMIRPUR' },
  { name: 'Hamirpur', value: 'HAMIRPUR' },
  { name: 'Hanumangarh', value: 'HANUMANGARH' },
  { name: 'Hapur (Panchsheel Nagar)', value: 'HAPUR (PANCHSHEEL NAGAR)' },
  { name: 'Harda', value: 'HARDA' },
  { name: 'Hardoi', value: 'HARDOI' },
  { name: 'Haridwar', value: 'HARIDWAR' },
  { name: 'Hassan', value: 'HASSAN' },
  { name: 'Hathras', value: 'HATHRAS' },
  { name: 'Haveri', value: 'HAVERI' },
  { name: 'Hazaribag', value: 'HAZARIBAG' },
  { name: 'Hingoli', value: 'HINGOLI' },
  { name: 'Hisar', value: 'HISAR' },
  { name: 'Hojai', value: 'HOJAI' },
  { name: 'Hooghly', value: 'HOOGHLY' },
  { name: 'Hoshangabad', value: 'HOSHANGABAD' },
  { name: 'Hoshiarpur', value: 'HOSHIARPUR' },
  { name: 'Howrah', value: 'HOWRAH' },
  { name: 'Hyderabad', value: 'HYDERABAD' },
  { name: 'Idukki', value: 'IDUKKI' },
  { name: 'Imphal East', value: 'IMPHAL EAST' },
  { name: 'Imphal West', value: 'IMPHAL WEST' },
  { name: 'Indore', value: 'INDORE' },
  { name: 'Jabalpur', value: 'JABALPUR' },
  { name: 'Jagatsinghapur', value: 'JAGATSINGHAPUR' },
  { name: 'Jagtial', value: 'JAGTIAL' },
  { name: 'Jaipur', value: 'JAIPUR' },
  { name: 'Jaisalmer', value: 'JAISALMER' },
  { name: 'Jajpur', value: 'JAJPUR' },
  { name: 'Jalandhar', value: 'JALANDHAR' },
  { name: 'Jalaun', value: 'JALAUN' },
  { name: 'Jalgaon', value: 'JALGAON' },
  { name: 'Jalna', value: 'JALNA' },
  { name: 'Jalore', value: 'JALORE' },
  { name: 'Jalpaiguri', value: 'JALPAIGURI' },
  { name: 'Jammu', value: 'JAMMU' },
  { name: 'Jamnagar', value: 'JAMNAGAR' },
  { name: 'Jamtara', value: 'JAMTARA' },
  { name: 'Jamui', value: 'JAMUI' },
  { name: 'Jangaon', value: 'JANGAON' },
  { name: 'Janjgir-Champa', value: 'JANJGIR-CHAMPA' },
  { name: 'Jashpur', value: 'JASHPUR' },
  { name: 'Jaunpur', value: 'JAUNPUR' },
  { name: 'Jayashankar Bhoopalpally', value: 'JAYASHANKAR BHOOPALPALLY' },
  { name: 'Jehanabad', value: 'JEHANABAD' },
  { name: 'Jhabua', value: 'JHABUA' },
  { name: 'Jhajjar', value: 'JHAJJAR' },
  { name: 'Jhalawar', value: 'JHALAWAR' },
  { name: 'Jhansi', value: 'JHANSI' },
  { name: 'Jharsuguda', value: 'JHARSUGUDA' },
  { name: 'Jhunjhunu', value: 'JHUNJHUNU' },
  { name: 'Jind', value: 'JIND' },
  { name: 'Jiribam', value: 'JIRIBAM' },
  { name: 'Jodhpur', value: 'JODHPUR' },
  { name: 'Jogulamba Gadwal', value: 'JOGULAMBA GADWAL' },
  { name: 'Jorhat', value: 'JORHAT' },
  { name: 'Junagadh', value: 'JUNAGADH' },
  { name: 'Kabirdham (Kawardha)', value: 'KABIRDHAM (KAWARDHA)' },
  { name: 'Kachchh', value: 'KACHCHH' },
  { name: 'Kadmath', value: 'KADMATH' },
  { name: 'Kaimur (Bhabua)', value: 'KAIMUR (BHABUA)' },
  { name: 'Kaithal', value: 'KAITHAL' },
  { name: 'Kakching', value: 'KAKCHING' },
  { name: 'Kalaburagi (Gulbarga)', value: 'KALABURAGI (GULBARGA)' },
  { name: 'Kalahandi', value: 'KALAHANDI' },
  { name: 'Kalimpong', value: 'KALIMPONG' },
  { name: 'Kalpeni', value: 'KALPENI' },
  { name: 'Kamareddy', value: 'KAMAREDDY' },
  { name: 'Kamjong', value: 'KAMJONG' },
  { name: 'Kamrup', value: 'KAMRUP' },
  { name: 'Kamrup Metropolitan', value: 'KAMRUP METROPOLITAN' },
  { name: 'Kanchipuram', value: 'KANCHIPURAM' },
  { name: 'Kandhamal', value: 'KANDHAMAL' },
  { name: 'Kangpokpi', value: 'KANGPOKPI' },
  { name: 'Kangra', value: 'KANGRA' },
  { name: 'Kanker (North Bastar)', value: 'KANKER (NORTH BASTAR)' },
  { name: 'Kannauj', value: 'KANNAUJ' },
  { name: 'Kannur', value: 'KANNUR' },
  { name: 'Kanpur Dehat', value: 'KANPUR DEHAT' },
  { name: 'Kanpur Nagar', value: 'KANPUR NAGAR' },
  { name: 'Kanshiram Nagar (Kasganj)', value: 'KANSHIRAM NAGAR (KASGANJ)' },
  { name: 'Kanyakumari', value: 'KANYAKUMARI' },
  { name: 'Kapurthala', value: 'KAPURTHALA' },
  { name: 'Karaikal', value: 'KARAIKAL' },
  { name: 'Karauli', value: 'KARAULI' },
  { name: 'Karbi Anglong', value: 'KARBI ANGLONG' },
  { name: 'Kargil', value: 'KARGIL' },
  { name: 'Karimganj', value: 'KARIMGANJ' },
  { name: 'Karimnagar', value: 'KARIMNAGAR' },
  { name: 'Karnal', value: 'KARNAL' },
  { name: 'Karur', value: 'KARUR' },
  { name: 'Kasaragod', value: 'KASARAGOD' },
  { name: 'Kathua', value: 'KATHUA' },
  { name: 'Katihar', value: 'KATIHAR' },
  { name: 'Katni', value: 'KATNI' },
  { name: 'Kaushambi', value: 'KAUSHAMBI' },
  { name: 'Kavaratti', value: 'KAVARATTI' },
  { name: 'Kendrapara', value: 'KENDRAPARA' },
  { name: 'Kendujhar (Keonjhar)', value: 'KENDUJHAR (KEONJHAR)' },
  { name: 'Khagaria', value: 'KHAGARIA' },
  { name: 'Khammam', value: 'KHAMMAM' },
  { name: 'Khandwa', value: 'KHANDWA' },
  { name: 'Khargone', value: 'KHARGONE' },
  { name: 'Kheda (Nadiad)', value: 'KHEDA (NADIAD)' },
  { name: 'Khordha', value: 'KHORDHA' },
  { name: 'Khowai', value: 'KHOWAI' },
  { name: 'Khunti', value: 'KHUNTI' },
  { name: 'Kilthan', value: 'KILTHAN' },
  { name: 'Kinnaur', value: 'KINNAUR' },
  { name: 'Kiphire', value: 'KIPHIRE' },
  { name: 'Kishanganj', value: 'KISHANGANJ' },
  { name: 'Kishtwar', value: 'KISHTWAR' },
  { name: 'Kodagu', value: 'KODAGU' },
  { name: 'Koderma', value: 'KODERMA' },
  { name: 'Kohima', value: 'KOHIMA' },
  { name: 'Kokrajhar', value: 'KOKRAJHAR' },
  { name: 'Kolar', value: 'KOLAR' },
  { name: 'Kolasib', value: 'KOLASIB' },
  { name: 'Kolhapur', value: 'KOLHAPUR' },
  { name: 'Kolkata', value: 'KOLKATA' },
  { name: 'Kollam', value: 'KOLLAM' },
  { name: 'Komaram Bheem Asifabad', value: 'KOMARAM BHEEM ASIFABAD' },
  { name: 'Kondagaon', value: 'KONDAGAON' },
  { name: 'Koppal', value: 'KOPPAL' },
  { name: 'Koraput', value: 'KORAPUT' },
  { name: 'Korba', value: 'KORBA' },
  { name: 'Korea (Koriya)', value: 'KOREA (KORIYA)' },
  { name: 'Kota', value: 'KOTA' },
  { name: 'Kottayam', value: 'KOTTAYAM' },
  { name: 'Kozhikode', value: 'KOZHIKODE' },
  { name: 'Kra Daadi', value: 'KRA DAADI' },
  { name: 'Krishna', value: 'KRISHNA' },
  { name: 'Krishnagiri', value: 'KRISHNAGIRI' },
  { name: 'Kulgam', value: 'KULGAM' },
  { name: 'Kullu', value: 'KULLU' },
  { name: 'Kupwara', value: 'KUPWARA' },
  { name: 'Kurnool', value: 'KURNOOL' },
  { name: 'Kurukshetra', value: 'KURUKSHETRA' },
  { name: 'Kurung Kumey', value: 'KURUNG KUMEY' },
  { name: 'Kushinagar (Padrauna)', value: 'KUSHINAGAR (PADRAUNA)' },
  { name: 'Lahaul &amp; Spiti', value: 'LAHAUL &AMP; SPITI' },
  { name: 'Lakhimpur', value: 'LAKHIMPUR' },
  { name: 'Lakhimpur - Kheri', value: 'LAKHIMPUR - KHERI' },
  { name: 'Lakhisarai', value: 'LAKHISARAI' },
  { name: 'Lalitpur', value: 'LALITPUR' },
  { name: 'Latehar', value: 'LATEHAR' },
  { name: 'Latur', value: 'LATUR' },
  { name: 'Lawngtlai', value: 'LAWNGTLAI' },
  { name: 'Leh', value: 'LEH' },
  { name: 'Lohardaga', value: 'LOHARDAGA' },
  { name: 'Lohit', value: 'LOHIT' },
  { name: 'Longding', value: 'LONGDING' },
  { name: 'Longleng', value: 'LONGLENG' },
  { name: 'Lower Dibang Valley', value: 'LOWER DIBANG VALLEY' },
  { name: 'Lower Siang', value: 'LOWER SIANG' },
  { name: 'Lower Subansiri', value: 'LOWER SUBANSIRI' },
  { name: 'Lucknow', value: 'LUCKNOW' },
  { name: 'Ludhiana', value: 'LUDHIANA' },
  { name: 'Lunglei', value: 'LUNGLEI' },
  { name: 'Madhepura', value: 'MADHEPURA' },
  { name: 'Madhubani', value: 'MADHUBANI' },
  { name: 'Madurai', value: 'MADURAI' },
  { name: 'Mahabubabad', value: 'MAHABUBABAD' },
  { name: 'Mahabubnagar', value: 'MAHABUBNAGAR' },
  { name: 'Maharajganj', value: 'MAHARAJGANJ' },
  { name: 'Mahasamund', value: 'MAHASAMUND' },
  { name: 'Mahe', value: 'MAHE' },
  { name: 'Mahendragarh', value: 'MAHENDRAGARH' },
  { name: 'Mahisagar', value: 'MAHISAGAR' },
  { name: 'Mahoba', value: 'MAHOBA' },
  { name: 'Mainpuri', value: 'MAINPURI' },
  { name: 'Majuli', value: 'MAJULI' },
  { name: 'Malappuram', value: 'MALAPPURAM' },
  { name: 'Malda', value: 'MALDA' },
  { name: 'Malkangiri', value: 'MALKANGIRI' },
  { name: 'Mamit', value: 'MAMIT' },
  { name: 'Mancherial', value: 'MANCHERIAL' },
  { name: 'Mandi', value: 'MANDI' },
  { name: 'Mandla', value: 'MANDLA' },
  { name: 'Mandsaur', value: 'MANDSAUR' },
  { name: 'Mandya', value: 'MANDYA' },
  { name: 'Mansa', value: 'MANSA' },
  { name: 'Mathura', value: 'MATHURA' },
  { name: 'Mau', value: 'MAU' },
  { name: 'Mayurbhanj', value: 'MAYURBHANJ' },
  { name: 'Medak', value: 'MEDAK' },
  { name: 'Medchal', value: 'MEDCHAL' },
  { name: 'Meerut', value: 'MEERUT' },
  { name: 'Mehsana', value: 'MEHSANA' },
  { name: 'Mewat', value: 'MEWAT' },
  { name: 'Minicoy', value: 'MINICOY' },
  { name: 'Mirzapur', value: 'MIRZAPUR' },
  { name: 'Moga', value: 'MOGA' },
  { name: 'Mokokchung', value: 'MOKOKCHUNG' },
  { name: 'Mon', value: 'MON' },
  { name: 'Moradabad', value: 'MORADABAD' },
  { name: 'Morbi', value: 'MORBI' },
  { name: 'Morena', value: 'MORENA' },
  { name: 'Morigaon', value: 'MORIGAON' },
  { name: 'Muktsar', value: 'MUKTSAR' },
  { name: 'Mumbai City', value: 'MUMBAI CITY' },
  { name: 'Mumbai Suburban', value: 'MUMBAI SUBURBAN' },
  { name: 'Mungeli', value: 'MUNGELI' },
  { name: 'Munger (Monghyr)', value: 'MUNGER (MONGHYR)' },
  { name: 'Murshidabad', value: 'MURSHIDABAD' },
  { name: 'Muzaffarnagar', value: 'MUZAFFARNAGAR' },
  { name: 'Muzaffarpur', value: 'MUZAFFARPUR' },
  { name: 'Mysuru (Mysore)', value: 'MYSURU (MYSORE)' },
  { name: 'Nabarangpur', value: 'NABARANGPUR' },
  { name: 'Nadia', value: 'NADIA' },
  { name: 'Nagaon', value: 'NAGAON' },
  { name: 'Nagapattinam', value: 'NAGAPATTINAM' },
  { name: 'Nagarkurnool', value: 'NAGARKURNOOL' },
  { name: 'Nagaur', value: 'NAGAUR' },
  { name: 'Nagpur', value: 'NAGPUR' },
  { name: 'Nainital', value: 'NAINITAL' },
  { name: 'Nalanda', value: 'NALANDA' },
  { name: 'Nalbari', value: 'NALBARI' },
  { name: 'Nalgonda', value: 'NALGONDA' },
  { name: 'Namakkal', value: 'NAMAKKAL' },
  { name: 'Namsai', value: 'NAMSAI' },
  { name: 'Nanded', value: 'NANDED' },
  { name: 'Nandurbar', value: 'NANDURBAR' },
  { name: 'Narayanpur', value: 'NARAYANPUR' },
  { name: 'Narmada (Rajpipla)', value: 'NARMADA (RAJPIPLA)' },
  { name: 'Narsinghpur', value: 'NARSINGHPUR' },
  { name: 'Nashik', value: 'NASHIK' },
  { name: 'Navsari', value: 'NAVSARI' },
  { name: 'Nawada', value: 'NAWADA' },
  {
    name: 'Nawanshahr (Shahid Bhagat Singh Nagar)',
    value: 'NAWANSHAHR (SHAHID BHAGAT SINGH NAGAR)',
  },
  { name: 'Nayagarh', value: 'NAYAGARH' },
  { name: 'Neemuch', value: 'NEEMUCH' },
  { name: 'Nellore', value: 'NELLORE' },
  { name: 'New Delhi', value: 'NEW DELHI' },
  { name: 'Nilgiris', value: 'NILGIRIS' },
  { name: 'Nirmal', value: 'NIRMAL' },
  { name: 'Nizamabad', value: 'NIZAMABAD' },
  { name: 'Noney', value: 'NONEY' },
  { name: 'North 24 Parganas', value: 'NORTH 24 PARGANAS' },
  { name: 'North Delhi', value: 'NORTH DELHI' },
  { name: 'North East  Delhi', value: 'NORTH EAST  DELHI' },
  { name: 'North Garo Hills', value: 'NORTH GARO HILLS' },
  { name: 'North Goa', value: 'NORTH GOA' },
  { name: 'North Sikkim', value: 'NORTH SIKKIM' },
  { name: 'North Tripura', value: 'NORTH TRIPURA' },
  { name: 'North West  Delhi', value: 'NORTH WEST  DELHI' },
  { name: 'Nuapada', value: 'NUAPADA' },
  { name: 'Osmanabad', value: 'OSMANABAD' },
  { name: 'Pakur', value: 'PAKUR' },
  { name: 'Palakkad', value: 'PALAKKAD' },
  { name: 'Palamu', value: 'PALAMU' },
  { name: 'Palghar', value: 'PALGHAR' },
  { name: 'Pali', value: 'PALI' },
  { name: 'Palwal', value: 'PALWAL' },
  { name: 'Panchkula', value: 'PANCHKULA' },
  { name: 'Panchmahal (Godhra)', value: 'PANCHMAHAL (GODHRA)' },
  { name: 'Panipat', value: 'PANIPAT' },
  { name: 'Panna', value: 'PANNA' },
  { name: 'Papum Pare', value: 'PAPUM PARE' },
  { name: 'Parbhani', value: 'PARBHANI' },
  {
    name: 'Paschim Medinipur (West Medinipur)',
    value: 'PASCHIM MEDINIPUR (WEST MEDINIPUR)',
  },
  { name: 'Patan', value: 'PATAN' },
  { name: 'Pathanamthitta', value: 'PATHANAMTHITTA' },
  { name: 'Pathankot', value: 'PATHANKOT' },
  { name: 'Patiala', value: 'PATIALA' },
  { name: 'Patna', value: 'PATNA' },
  { name: 'Pauri Garhwal', value: 'PAURI GARHWAL' },
  { name: 'Peddapalli', value: 'PEDDAPALLI' },
  { name: 'Perambalur', value: 'PERAMBALUR' },
  { name: 'Peren', value: 'PEREN' },
  { name: 'Phek', value: 'PHEK' },
  { name: 'Pherzawl', value: 'PHERZAWL' },
  { name: 'Pilibhit', value: 'PILIBHIT' },
  { name: 'Pithoragarh', value: 'PITHORAGARH' },
  { name: 'Pondicherry', value: 'PONDICHERRY' },
  { name: 'Poonch', value: 'POONCH' },
  { name: 'Porbandar', value: 'PORBANDAR' },
  { name: 'Prakasam', value: 'PRAKASAM' },
  { name: 'Pratapgarh', value: 'PRATAPGARH' },
  { name: 'Pratapgarh', value: 'PRATAPGARH' },
  { name: 'Pudukkottai', value: 'PUDUKKOTTAI' },
  { name: 'Pulwama', value: 'PULWAMA' },
  { name: 'Pune', value: 'PUNE' },
  {
    name: 'Purba Medinipur (East Medinipur)',
    value: 'PURBA MEDINIPUR (EAST MEDINIPUR)',
  },
  { name: 'Puri', value: 'PURI' },
  { name: 'Purnia (Purnea)', value: 'PURNIA (PURNEA)' },
  { name: 'Purulia', value: 'PURULIA' },
  { name: 'RaeBareli', value: 'RAEBARELI' },
  { name: 'Raichur', value: 'RAICHUR' },
  { name: 'Raigad', value: 'RAIGAD' },
  { name: 'Raigarh', value: 'RAIGARH' },
  { name: 'Raipur', value: 'RAIPUR' },
  { name: 'Raisen', value: 'RAISEN' },
  { name: 'Rajanna Sircilla', value: 'RAJANNA SIRCILLA' },
  { name: 'Rajgarh', value: 'RAJGARH' },
  { name: 'Rajkot', value: 'RAJKOT' },
  { name: 'Rajnandgaon', value: 'RAJNANDGAON' },
  { name: 'Rajouri', value: 'RAJOURI' },
  { name: 'Rajsamand', value: 'RAJSAMAND' },
  { name: 'Ramanagara', value: 'RAMANAGARA' },
  { name: 'Ramanathapuram', value: 'RAMANATHAPURAM' },
  { name: 'Ramban', value: 'RAMBAN' },
  { name: 'Ramgarh', value: 'RAMGARH' },
  { name: 'Rampur', value: 'RAMPUR' },
  { name: 'Ranchi', value: 'RANCHI' },
  { name: 'Rangareddy', value: 'RANGAREDDY' },
  { name: 'Ratlam', value: 'RATLAM' },
  { name: 'Ratnagiri', value: 'RATNAGIRI' },
  { name: 'Rayagada', value: 'RAYAGADA' },
  { name: 'Reasi', value: 'REASI' },
  { name: 'Rewa', value: 'REWA' },
  { name: 'Rewari', value: 'REWARI' },
  { name: 'Ri Bhoi', value: 'RI BHOI' },
  { name: 'Rohtak', value: 'ROHTAK' },
  { name: 'Rohtas', value: 'ROHTAS' },
  { name: 'Rudraprayag', value: 'RUDRAPRAYAG' },
  { name: 'Rupnagar', value: 'RUPNAGAR' },
  { name: 'Sabarkantha (Himmatnagar)', value: 'SABARKANTHA (HIMMATNAGAR)' },
  { name: 'Sagar', value: 'SAGAR' },
  { name: 'Saharanpur', value: 'SAHARANPUR' },
  { name: 'Saharsa', value: 'SAHARSA' },
  { name: 'Sahibganj', value: 'SAHIBGANJ' },
  {
    name: 'Sahibzada Ajit Singh Nagar (Mohali)',
    value: 'SAHIBZADA AJIT SINGH NAGAR (MOHALI)',
  },
  { name: 'Saiha', value: 'SAIHA' },
  { name: 'Salem', value: 'SALEM' },
  { name: 'Samastipur', value: 'SAMASTIPUR' },
  { name: 'Samba', value: 'SAMBA' },
  { name: 'Sambalpur', value: 'SAMBALPUR' },
  { name: 'Sambhal (Bhim Nagar)', value: 'SAMBHAL (BHIM NAGAR)' },
  { name: 'Sangareddy', value: 'SANGAREDDY' },
  { name: 'Sangli', value: 'SANGLI' },
  { name: 'Sangrur', value: 'SANGRUR' },
  { name: 'Sant Kabir Nagar', value: 'SANT KABIR NAGAR' },
  { name: 'Saran', value: 'SARAN' },
  { name: 'Satara', value: 'SATARA' },
  { name: 'Satna', value: 'SATNA' },
  { name: 'Sawai Madhopur', value: 'SAWAI MADHOPUR' },
  { name: 'Sehore', value: 'SEHORE' },
  { name: 'Senapati', value: 'SENAPATI' },
  { name: 'Seoni', value: 'SEONI' },
  { name: 'Sepahijala', value: 'SEPAHIJALA' },
  { name: 'Seraikela-Kharsawan', value: 'SERAIKELA-KHARSAWAN' },
  { name: 'Serchhip', value: 'SERCHHIP' },
  { name: 'Shahdara', value: 'SHAHDARA' },
  { name: 'Shahdol', value: 'SHAHDOL' },
  { name: 'Shahjahanpur', value: 'SHAHJAHANPUR' },
  { name: 'Shajapur', value: 'SHAJAPUR' },
  { name: 'Shamali (Prabuddh Nagar)', value: 'SHAMALI (PRABUDDH NAGAR)' },
  { name: 'Sheikhpura', value: 'SHEIKHPURA' },
  { name: 'Sheohar', value: 'SHEOHAR' },
  { name: 'Sheopur', value: 'SHEOPUR' },
  { name: 'Shimla', value: 'SHIMLA' },
  { name: 'Shivamogga (Shimoga)', value: 'SHIVAMOGGA (SHIMOGA)' },
  { name: 'Shivpuri', value: 'SHIVPURI' },
  { name: 'Shopian', value: 'SHOPIAN' },
  { name: 'Shravasti', value: 'SHRAVASTI' },
  { name: 'Siang', value: 'SIANG' },
  { name: 'Siddharth Nagar', value: 'SIDDHARTH NAGAR' },
  { name: 'Siddipet', value: 'SIDDIPET' },
  { name: 'Sidhi', value: 'SIDHI' },
  { name: 'Sikar', value: 'SIKAR' },
  { name: 'Simdega', value: 'SIMDEGA' },
  { name: 'Sindhudurg', value: 'SINDHUDURG' },
  { name: 'Singrauli', value: 'SINGRAULI' },
  { name: 'Sirmaur (Sirmour)', value: 'SIRMAUR (SIRMOUR)' },
  { name: 'Sirohi', value: 'SIROHI' },
  { name: 'Sirsa', value: 'SIRSA' },
  { name: 'Sitamarhi', value: 'SITAMARHI' },
  { name: 'Sitapur', value: 'SITAPUR' },
  { name: 'Sivaganga', value: 'SIVAGANGA' },
  { name: 'Sivasagar', value: 'SIVASAGAR' },
  { name: 'Siwan', value: 'SIWAN' },
  { name: 'Solan', value: 'SOLAN' },
  { name: 'Solapur', value: 'SOLAPUR' },
  { name: 'Sonbhadra', value: 'SONBHADRA' },
  { name: 'Sonepur', value: 'SONEPUR' },
  { name: 'Sonipat', value: 'SONIPAT' },
  { name: 'Sonitpur', value: 'SONITPUR' },
  { name: 'South 24 Parganas', value: 'SOUTH 24 PARGANAS' },
  { name: 'South Delhi', value: 'SOUTH DELHI' },
  { name: 'South East Delhi', value: 'SOUTH EAST DELHI' },
  { name: 'South Garo Hills', value: 'SOUTH GARO HILLS' },
  { name: 'South Goa', value: 'SOUTH GOA' },
  { name: 'South Salmara-Mankachar', value: 'SOUTH SALMARA-MANKACHAR' },
  { name: 'South Sikkim', value: 'SOUTH SIKKIM' },
  { name: 'South Tripura', value: 'SOUTH TRIPURA' },
  { name: 'South West  Delhi', value: 'SOUTH WEST  DELHI' },
  { name: 'South West Garo Hills ', value: 'SOUTH WEST GARO HILLS ' },
  { name: 'South West Khasi Hills', value: 'SOUTH WEST KHASI HILLS' },
  { name: 'Sri Ganganagar', value: 'SRI GANGANAGAR' },
  { name: 'Srikakulam', value: 'SRIKAKULAM' },
  { name: 'Srinagar', value: 'SRINAGAR' },
  { name: 'Sukma', value: 'SUKMA' },
  { name: 'Sultanpur', value: 'SULTANPUR' },
  { name: 'Sundargarh', value: 'SUNDARGARH' },
  { name: 'Supaul', value: 'SUPAUL' },
  { name: 'Surajpur  ', value: 'SURAJPUR  ' },
  { name: 'Surat', value: 'SURAT' },
  { name: 'Surendranagar', value: 'SURENDRANAGAR' },
  { name: 'Surguja', value: 'SURGUJA' },
  { name: 'Suryapet', value: 'SURYAPET' },
  { name: 'Tamenglong', value: 'TAMENGLONG' },
  { name: 'Tapi (Vyara)', value: 'TAPI (VYARA)' },
  { name: 'Tarn Taran', value: 'TARN TARAN' },
  { name: 'Tawang', value: 'TAWANG' },
  { name: 'Tehri Garhwal', value: 'TEHRI GARHWAL' },
  { name: 'Tengnoupal', value: 'TENGNOUPAL' },
  { name: 'Thane', value: 'THANE' },
  { name: 'Thanjavur', value: 'THANJAVUR' },
  { name: 'Theni', value: 'THENI' },
  { name: 'Thiruvananthapuram', value: 'THIRUVANANTHAPURAM' },
  { name: 'Thoothukudi (Tuticorin)', value: 'THOOTHUKUDI (TUTICORIN)' },
  { name: 'Thoubal', value: 'THOUBAL' },
  { name: 'Thrissur', value: 'THRISSUR' },
  { name: 'Tikamgarh', value: 'TIKAMGARH' },
  { name: 'Tinsukia', value: 'TINSUKIA' },
  { name: 'Tirap', value: 'TIRAP' },
  { name: 'Tiruchirappalli', value: 'TIRUCHIRAPPALLI' },
  { name: 'Tirunelveli', value: 'TIRUNELVELI' },
  { name: 'Tiruppur', value: 'TIRUPPUR' },
  { name: 'Tiruvallur', value: 'TIRUVALLUR' },
  { name: 'Tiruvannamalai', value: 'TIRUVANNAMALAI' },
  { name: 'Tiruvarur', value: 'TIRUVARUR' },
  { name: 'Tonk', value: 'TONK' },
  { name: 'Tuensang', value: 'TUENSANG' },
  { name: 'Tumakuru (Tumkur)', value: 'TUMAKURU (TUMKUR)' },
  { name: 'Udaipur', value: 'UDAIPUR' },
  { name: 'Udalguri', value: 'UDALGURI' },
  { name: 'Udham Singh Nagar', value: 'UDHAM SINGH NAGAR' },
  { name: 'Udhampur', value: 'UDHAMPUR' },
  { name: 'Udupi', value: 'UDUPI' },
  { name: 'Ujjain', value: 'UJJAIN' },
  { name: 'Ukhrul', value: 'UKHRUL' },
  { name: 'Umaria', value: 'UMARIA' },
  { name: 'Una', value: 'UNA' },
  { name: 'Unakoti', value: 'UNAKOTI' },
  { name: 'Unnao', value: 'UNNAO' },
  { name: 'Upper Siang', value: 'UPPER SIANG' },
  { name: 'Upper Subansiri', value: 'UPPER SUBANSIRI' },
  {
    name: 'Uttar Dinajpur (North Dinajpur)',
    value: 'UTTAR DINAJPUR (NORTH DINAJPUR)',
  },
  { name: 'Uttara Kannada (Karwar)', value: 'UTTARA KANNADA (KARWAR)' },
  { name: 'Uttarkashi', value: 'UTTARKASHI' },
  { name: 'Vadodara', value: 'VADODARA' },
  { name: 'Vaishali', value: 'VAISHALI' },
  { name: 'Valsad', value: 'VALSAD' },
  { name: 'Varanasi', value: 'VARANASI' },
  { name: 'Vellore', value: 'VELLORE' },
  { name: 'Vidisha', value: 'VIDISHA' },
  { name: 'Vijayapura (Bijapur)', value: 'VIJAYAPURA (BIJAPUR)' },
  { name: 'Vikarabad', value: 'VIKARABAD' },
  { name: 'Viluppuram', value: 'VILUPPURAM' },
  { name: 'Virudhunagar', value: 'VIRUDHUNAGAR' },
  { name: 'Visakhapatnam', value: 'VISAKHAPATNAM' },
  { name: 'Vizianagaram', value: 'VIZIANAGARAM' },
  { name: 'Wanaparthy', value: 'WANAPARTHY' },
  { name: 'Warangal (Rural)', value: 'WARANGAL (RURAL)' },
  { name: 'Warangal (Urban)', value: 'WARANGAL (URBAN)' },
  { name: 'Wardha', value: 'WARDHA' },
  { name: 'Washim', value: 'WASHIM' },
  { name: 'Wayanad', value: 'WAYANAD' },
  { name: 'West Champaran', value: 'WEST CHAMPARAN' },
  { name: 'West Delhi', value: 'WEST DELHI' },
  { name: 'West Garo Hills', value: 'WEST GARO HILLS' },
  { name: 'West Godavari', value: 'WEST GODAVARI' },
  { name: 'West Jaintia Hills', value: 'WEST JAINTIA HILLS' },
  { name: 'West Kameng', value: 'WEST KAMENG' },
  { name: 'West Karbi Anglong', value: 'WEST KARBI ANGLONG' },
  { name: 'West Khasi Hills', value: 'WEST KHASI HILLS' },
  { name: 'West Siang', value: 'WEST SIANG' },
  { name: 'West Sikkim', value: 'WEST SIKKIM' },
  { name: 'West Singhbhum', value: 'WEST SINGHBHUM' },
  { name: 'West Tripura', value: 'WEST TRIPURA' },
  { name: 'Wokha', value: 'WOKHA' },
  { name: 'YSR Kadapa', value: 'YSR KADAPA' },
  { name: 'Yadadri Bhuvanagiri', value: 'YADADRI BHUVANAGIRI' },
  { name: 'Yadgir', value: 'YADGIR' },
  { name: 'Yamunanagar', value: 'YAMUNANAGAR' },
  { name: 'Yanam', value: 'YANAM' },
  { name: 'Yavatmal', value: 'YAVATMAL' },
  { name: 'Zunheboto', value: 'ZUNHEBOTO' },
];

const DATA_STEP_1 = {
  name: {
    label: 'Name',
    type: 'text',
    // options: CITY_OPTIONS,
    validations: {
      required: true,
    },
    errors: {},
    placeholder: 'Name',
  },
  stateId: {
    label: 'State',
    type: 'select',
    options: [],
    url: '/states',
    isDynamic: true,
    validations: {
      required: true,
    },
    errors: {},
    placeholder: 'State',
  },
};

const STEP_ITEMS = [{ label: 'Basic Details', data: DATA_STEP_1 }];

export { STEP_ITEMS as CITY_FORM_STEPS };
